import React, { useEffect, useRef, useState } from 'react';
import { Loader2, Send, Sparkles } from 'lucide-react';
import { useCrm } from '../../context/CrmContext';

type ChatItem={id:string;role:'user'|'assistant';text:string};

export const FigmaEvaView:React.FC=()=>{
  const{deals,tasks,setCurrentTab,setSelectedDealId}=useCrm();
  const[messages,setMessages]=useState<ChatItem[]>([{id:'hello',role:'assistant',text:'Доброе утро. Я проверила CRM и вижу приоритетные действия на сегодня.\nСобрала их ниже и могу выполнить часть действий сама.'}]);
  const[draft,setDraft]=useState(''); const[busy,setBusy]=useState(false); const endRef=useRef<HTMLDivElement|null>(null);
  const awaitingReply=deals.filter(d=>['proposal_sent','negotiation'].includes(d.stage)).length;
  const deadlines=tasks.filter(t=>!t.completed&&new Date(t.deadline).getTime()<Date.now()+2*864e5).length;
  const stalled=deals.filter(d=>Date.now()-new Date(d.updatedAt).getTime()>5*864e5).length;
  const payment=deals.filter(d=>d.stage==='prepayment').length;
  const followup=deals.filter(d=>d.stage==='proposal_sent').length;
  const priority=deals.filter(d=>!['closed_won','closed_lost'].includes(d.stage)).slice(0,3);
  useEffect(()=>{requestAnimationFrame(()=>endRef.current?.scrollIntoView({block:'end'}))},[messages.length,busy]);
  async function send(textOverride?:string){const text=(textOverride??draft).trim();if(!text||busy)return;setMessages(v=>[...v,{id:`u${Date.now()}`,role:'user',text}]);setDraft('');setBusy(true);try{const r=await fetch('/api/assistant',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'chat',message:text})});const data=await r.json();if(!r.ok)throw new Error(data.error||'AI не ответил');setMessages(v=>[...v,{id:`a${Date.now()}`,role:'assistant',text:String(data.reply||'Готово.')}])}catch(e){setMessages(v=>[...v,{id:`e${Date.now()}`,role:'assistant',text:`Ошибка: ${e instanceof Error?e.message:'не удалось выполнить команду'}`}])}finally{setBusy(false)}}
  async function plan(){if(busy)return;setBusy(true);try{const r=await fetch('/api/assistant',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'run',notify:false})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Проверка не выполнена');setMessages(v=>[...v,{id:`p${Date.now()}`,role:'assistant',text:'План дня обновлён по текущей базе CRM.'}])}catch(e){setMessages(v=>[...v,{id:`p${Date.now()}`,role:'assistant',text:`Не удалось обновить план: ${e instanceof Error?e.message:'ошибка'}`}])}finally{setBusy(false)}}
  const cards=[[awaitingReply,'клиента ждут ответа','#f8e5d2'],[deadlines,'проекта близки к дедлайну','#f4dde2'],[stalled,'сделки без движения','#e7ddf8'],[payment,'счёт ждёт оплаты','#ddeaf7'],[followup,'КП требуют follow-up','#e5f1e8']] as const;
  const quick=['Кто требует ответа?','Что горит по срокам?','Сводка по оплатам','Follow-up клиентам'];
  return <div className="relative h-[1000px] min-w-[1080px] overflow-hidden bg-[#f7f5f2] text-[#1f1d1c]">
    <div className="absolute left-[42px] top-[26px] flex items-baseline gap-4"><h1 className="text-[34px] font-semibold leading-none tracking-[-.035em]">Чат с Евой</h1><span className="text-[13px] text-[#817a74]">AI-помощник по CRM, сделкам, срокам и перепискам</span></div>
    <div className="absolute right-[54px] top-[22px] flex h-[44px] w-[126px] items-center justify-around rounded-[22px] bg-white text-[18px]"><span>☼</span><span className="text-[#817a74]">◐</span></div>
    <button onClick={()=>void plan()} className="absolute right-[54px] top-[78px] h-[42px] w-[216px] rounded-[13px] bg-[#2a292b] text-[12px] text-white"><Sparkles size={13} className="mr-2 inline"/>Сформировать план дня</button>
    <section className="absolute left-[42px] right-[54px] top-[136px] h-[156px] rounded-[18px] border border-[#e8e3de] bg-white p-[20px]"><h2 className="text-[20px] font-semibold">Сегодня важно</h2><p className="text-[10px] text-[#817a74]">Ева собрала приоритеты по перепискам, оплатам и срокам</p><div className="mt-[16px] grid grid-cols-5 gap-[16px]">{cards.map(([n,label,bg])=><div key={label} className="flex h-[58px] items-center rounded-[13px] px-[14px]" style={{background:bg}}><b className="mr-[16px] text-[20px]">{n}</b><span className="text-[10px] font-medium">{label}</span></div>)}</div></section>
    <div className="absolute left-[42px] right-[54px] top-[310px] grid h-[688px] grid-cols-[730fr_484fr] gap-[20px]">
      <section className="flex min-h-0 flex-col overflow-hidden rounded-[18px] border border-[#e8e3de] bg-white"><header className="flex h-[63px] items-center border-b border-[#e8e3de] px-[20px]"><h2 className="text-[19px] font-semibold">Ева</h2><span className="ml-auto rounded-[10px] bg-[#e5f1e8] px-3 py-2 text-[10px] text-[#4d7c62]">● онлайн</span></header><div className="min-h-0 flex-1 overflow-y-auto p-[19px]">
        {messages.map(m=><div key={m.id} className={`mb-3 whitespace-pre-wrap rounded-[14px] px-4 py-3 text-[11px] leading-relaxed ${m.role==='user'?'ml-auto max-w-[70%] bg-[#ddeaf7]':'max-w-[82%] bg-[#fbfaf8]'}`}>{m.text}</div>)}
        {priority.map((d,i)=><div key={d.id} className="mb-3 flex h-[72px] items-center rounded-[13px] border border-[#e8e3de] px-[14px]"><span className="mr-4 grid h-[38px] w-[38px] place-items-center rounded-[12px] text-[12px] font-semibold" style={{background:['#f8e5d2','#f4dde2','#ddeaf7'][i]}}>{i+1}</span><div className="min-w-0"><b className="block truncate text-[11px]">{d.clientName} — {d.title}</b><span className="text-[9px] text-[#817a74]">{d.stage==='prepayment'?`Ждём оплату • ${new Intl.NumberFormat('ru-RU').format(d.amount)} ₽`:'Требует следующего действия'}</span></div><button onClick={()=>{setSelectedDealId(d.id);setCurrentTab('deals')}} className="ml-auto h-[32px] w-[126px] rounded-[10px] border border-[#e8e3de] bg-[#fbfaf8] text-[9px]">Открыть →</button></div>)}
        <div className="my-[12px] flex gap-[10px]">{quick.map(q=><button key={q} onClick={()=>setDraft(q)} className="rounded-[10px] bg-[#fbfaf8] px-3 py-2 text-[9px]">{q}</button>)}</div>{busy&&<div className="mb-3 flex w-fit items-center rounded-[14px] bg-[#fbfaf8] px-4 py-3"><Loader2 size={14} className="animate-spin"/></div>}<div ref={endRef}/>
      </div><footer className="flex h-[62px] items-center gap-[10px] border-t border-[#e8e3de] px-[19px]"><button className="h-[42px] w-[42px] rounded-[11px] border border-[#e8e3de] bg-[#fbfaf8]">＋</button><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}} placeholder="Спросить Еву или дать команду…" className="h-[42px] min-w-0 flex-1 rounded-[11px] border border-[#e8e3de] bg-[#fbfaf8] px-4 text-[11px] outline-none"/><button onClick={()=>void send()} disabled={busy} className="grid h-[42px] w-[88px] place-items-center rounded-[11px] bg-[#2a292b] text-white"><Send size={14}/></button></footer></section>
      <section className="overflow-hidden rounded-[18px] border border-[#e8e3de] bg-white p-[20px]"><h2 className="text-[19px] font-semibold">Что требует внимания</h2><h3 className="mt-4 text-[12px] font-semibold">Важные переписки</h3>{priority.slice(0,3).map((d,i)=><button key={d.id} onClick={()=>{setSelectedDealId(d.id);setCurrentTab('deals')}} className="mt-2 flex h-[58px] w-full items-center justify-between rounded-[12px] bg-[#fbfaf8] px-[14px] text-left"><div><b className="block text-[10px]">{d.clientName}</b><span className="text-[9px] text-[#817a74]">{d.title}</span></div><span className={`${i===1?'text-[#d98395]':'text-[#817a74]'} text-[9px]`}>{i===1?'16:00':'Сегодня'}</span></button>)}<h3 className="mt-5 text-[12px] font-semibold">Сроки и дедлайны</h3>{deals.filter(d=>activeStageLocal(d.stage)).slice(0,3).map((d,i)=><div key={d.id} className="mt-2 flex h-[58px] items-center justify-between rounded-[12px] bg-[#fbfaf8] px-[14px]"><div><b className="block text-[10px]">{d.clientName}</b><span className="text-[9px] text-[#817a74]">{d.title}</span></div><span className="text-[9px] text-[#817a74]">{i===0?'через 2 дня':i===1?'сегодня':'завтра'}</span></div>)}<div className="mt-4 rounded-[14px] bg-[#faf7f1] p-[14px]"><b className="text-[11px] text-[#d8a66d]">Рекомендация Евы</b><p className="mt-2 text-[10px] leading-relaxed">Сначала закройте переписки без ответа, затем проверьте оплаты и дедлайны активных проектов.</p><div className="mt-3 flex gap-2"><button className="rounded-[9px] border border-[#e8e3de] bg-white px-3 py-2 text-[9px]">Подготовить сообщение</button><button className="rounded-[9px] border border-[#e8e3de] bg-white px-3 py-2 text-[9px]">Создать задачу</button></div></div></section>
    </div>
  </div>;
};

function activeStageLocal(stage:string){return !['closed_won','closed_lost'].includes(stage)}
