import React, { useMemo, useState } from 'react';
import {
  ArrowLeft, CalendarDays, Circle, FileText, Home, MessageCircle,
  MoreHorizontal, Search,
} from 'lucide-react';
import { useCrm } from '../../context/CrmContext';
import type { Deal, DealStage } from '../../types/crm';
import { compactMoney, money, stageMeta } from './FigmaViews';

type Tab = 'dashboard'|'deals'|'pipeline'|'inbox'|'finance'|'project_calc'|'documents'|'ai_manager'|'calendar'|'settings';
const DAY = 24 * 60 * 60 * 1000;
const palette = ['#ddeafb','#f8e8d6','#f7dde4','#ddefe4','#e9e1fa'];
const stageOrder:DealStage[]=['lead','contacted','calculation','proposal_sent','negotiation','prepayment','production','ready','shipped','closed_won','closed_lost'];
const activeStage=(s:DealStage)=>!['closed_won','closed_lost'].includes(s);
const initials=(name='К')=>name.trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();
const shortDate=(value?:string)=>{if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(d).replace('.','')};
const monthLabel=()=>new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(new Date());
const mondayOf=(value:Date)=>{const d=new Date(value.getFullYear(),value.getMonth(),value.getDate());const wd=d.getDay()||7;d.setDate(d.getDate()-wd+1);return d};
const Empty:React.FC<{text:string}>=({text})=><div className="py-10 text-center text-[11px] text-[#8b8580]">{text}</div>;

const MobileCard:React.FC<React.PropsWithChildren<{className?:string}>>=({children,className=''})=><section className={`rounded-[16px] border border-[#e8e4de] bg-white ${className}`}>{children}</section>;
const MobileHeader:React.FC<{title:string;subtitle?:string;back?:()=>void}>=({title,subtitle,back})=><header className="flex min-h-[68px] items-start justify-between px-5 pt-5"><div className="min-w-0 flex items-start gap-2">{back&&<button onClick={back} className="mt-1 grid h-8 w-8 shrink-0 place-items-center rounded-full bg-white"><ArrowLeft size={17}/></button>}<div className="min-w-0"><h1 className="truncate text-[26px] font-semibold tracking-[-.035em] text-[#181a20]">{title}</h1>{subtitle&&<p className="mt-0.5 text-[11px] text-[#7b808b]">{subtitle}</p>}</div></div>{!back&&<span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-white text-[#181a20]"><Search size={17}/></span>}</header>;
const KpiMini:React.FC<{label:string;value:string|number;color:string}>=({label,value,color})=><MobileCard className="h-[82px] p-[10px]"><div className="flex items-center gap-2"><span className="h-[30px] w-[30px] shrink-0 rounded-[9px]" style={{background:color}}/><b className="truncate text-[16px] font-semibold">{value}</b></div><div className="mt-2 truncate text-[9px] text-[#7b808b]">{label}</div></MobileCard>;

const MobileBottomNav:React.FC<{moreOpen:boolean;setMoreOpen:(v:boolean)=>void}>=({moreOpen,setMoreOpen})=>{
  const{currentTab,setCurrentTab}=useCrm();const tab=String(currentTab);const go=(t:Tab)=>{setMoreOpen(false);setCurrentTab(t as any)};
  const items=[['dashboard','Главная',Home],['deals','Сделки',Circle],['inbox','Чаты',MessageCircle],['calendar','Календарь',CalendarDays],['more','Ещё',MoreHorizontal]] as const;
  return <>{moreOpen&&<div className="fixed inset-0 z-40 bg-black/20" onClick={()=>setMoreOpen(false)}><div onClick={e=>e.stopPropagation()} className="absolute bottom-[74px] left-3 right-3 rounded-[22px] border border-[#e8e4de] bg-white p-3 shadow-xl"><div className="grid grid-cols-2 gap-2">{[['pipeline','Воронка'],['finance','Экономика'],['project_calc','Расчёт проекта'],['documents','КП и договор'],['ai_manager','Чат с Евой'],['settings','Настройки']].map(([id,label])=><button key={id} onClick={()=>go(id as Tab)} className="rounded-[14px] bg-[#f7f5f1] px-4 py-3 text-left text-[12px] font-medium">{label}</button>)}</div></div></div>}<nav className="fixed bottom-0 left-0 right-0 z-50 mx-auto h-[64px] max-w-[430px] rounded-t-[22px] border border-[#e8e4de] bg-white px-2 pt-2 shadow-[0_-4px_20px_rgba(0,0,0,.04)]"><div className="grid grid-cols-5">{items.map(([id,label,Icon])=>{const active=id==='more'?['pipeline','finance','project_calc','documents','ai_manager','settings'].includes(tab):tab===id;return <button key={id} onClick={()=>id==='more'?setMoreOpen(!moreOpen):go(id as Tab)} className="flex flex-col items-center gap-1 text-[9px] text-[#7b808b]"><span className={`grid h-[34px] w-[58px] place-items-center rounded-[12px] ${active?'bg-[#232326] text-white':'text-[#181a20]'}`}><Icon size={15}/></span><span>{label}</span></button>})}</div></nav></>;
};

const MobileDashboard:React.FC=()=>{
  const{deals,tasks,payments,chatMessages,setCurrentTab,setIsCreateTaskOpen,setIsCreateInvoiceOpen}=useCrm();
  const active=deals.filter(d=>activeStage(d.stage));
  const paid=payments.filter(p=>p.direction==='inflow'&&p.status==='completed').reduce((s,p)=>s+p.amount,0);
  const unread=chatMessages.filter(m=>m.direction==='inbound'&&!m.isRead).length;
  const openTasks=tasks.filter(t=>!t.completed).sort((a,b)=>+new Date(a.deadline)-+new Date(b.deadline));
  const attention=deals.filter(d=>['proposal_sent','prepayment','production'].includes(d.stage)).slice(0,3);
  return <><MobileHeader title="Satori CRM" subtitle={new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}/><div className="px-5 pb-24"><div className="grid grid-cols-4 gap-[6px]"><KpiMini label="Заявки" value={deals.filter(d=>d.stage==='lead').length} color="#ddeafb"/><KpiMini label="Ответить" value={unread} color="#f8e8d6"/><KpiMini label="Дедлайн" value={openTasks.filter(t=>new Date(t.deadline).getTime()<Date.now()+2*DAY).length} color="#f7dde4"/><KpiMini label="В работе" value={compactMoney(active.reduce((s,d)=>s+d.amount,0)).replace(' ₽','').replace(' млн','м')} color="#ddefe4"/></div><MobileCard className="mt-4 p-[13px]"><h2 className="text-[16px] font-semibold">Требуют внимания</h2><div className="mt-3 space-y-2">{attention.length?attention.map((d,i)=><button key={d.id} onClick={()=>setCurrentTab('deals')} className="flex h-[56px] w-full items-center rounded-[12px] bg-[#fbfaf7] px-[10px] text-left"><span className="grid h-[30px] w-[30px] shrink-0 place-items-center rounded-full text-[10px]" style={{background:palette[(i+1)%palette.length]}}>{initials(d.clientName)}</span><span className="ml-[10px] min-w-0 flex-1"><b className="block truncate text-[12px]">{d.clientName}</b><span className="block truncate text-[10px] text-[#7b808b]">{d.title}</span></span><span className="ml-2 rounded-full bg-white px-3 py-2 text-[9px]">{stageMeta[d.stage].label}</span></button>):<Empty text="Срочных сделок нет"/>}</div></MobileCard><MobileCard className="mt-4 p-[13px]"><h2 className="text-[16px] font-semibold">Быстрые действия</h2><div className="mt-4 flex gap-2"><button onClick={()=>setCurrentTab('documents')} className="flex-1 rounded-full bg-[#ddefe4] px-2 py-2 text-[10px] font-medium">Создать КП</button><button onClick={()=>setIsCreateInvoiceOpen(true)} className="flex-1 rounded-full bg-[#ddeafb] px-2 py-2 text-[10px] font-medium">Выставить счёт</button><button onClick={()=>setIsCreateTaskOpen(true)} className="flex-1 rounded-full bg-[#e9e1fa] px-2 py-2 text-[10px] font-medium">Добавить задачу</button></div></MobileCard><MobileCard className="mt-4 p-[13px]"><h2 className="text-[16px] font-semibold">Ближайшие задачи</h2><div className="mt-4 space-y-3">{openTasks.slice(0,4).map(t=><div key={t.id} className="flex text-[12px]"><span className="w-[52px] shrink-0 text-[#7b808b]">{shortDate(t.deadline)}</span><span className="min-w-0 truncate">{t.title}</span></div>)}{!openTasks.length&&<Empty text="Открытых задач нет"/>}</div><div className="mt-4 border-t border-[#eeeae6] pt-3 text-[10px] text-[#7b808b]">Получено оплат: <b className="text-[#181a20]">{money(paid)}</b></div></MobileCard></div></>;
};

const DealCard:React.FC<{deal:Deal;open:()=>void}>=({deal,open})=><button onClick={open} className="w-full rounded-[16px] border border-[#e8e4de] bg-white p-[14px] text-left"><div className="flex items-start"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#f3e7dc] text-[11px]">{initials(deal.clientName)}</span><span className="ml-3 min-w-0 flex-1"><b className="block truncate text-[13px]">{deal.clientName}</b><span className="mt-0.5 block truncate text-[10px] text-[#7b808b]">{deal.title}</span></span><b className="ml-2 whitespace-nowrap text-[12px]">{compactMoney(deal.amount)}</b></div><div className="mt-3 flex items-center justify-between"><span className="rounded-full px-3 py-1.5 text-[9px]" style={{background:stageMeta[deal.stage].bg}}>{stageMeta[deal.stage].label}</span><span className="text-[10px] text-[#7b808b]">Подробнее →</span></div></button>;

const MobileDeals:React.FC=()=>{
  const{deals,selectedDealId,setSelectedDealId}=useCrm();const[filter,setFilter]=useState('all');
  const deal=selectedDealId?deals.find(d=>d.id===selectedDealId):null;if(deal)return <MobileDealDetail deal={deal} onBack={()=>setSelectedDealId(null)}/>;
  const shown=deals.filter(d=>filter==='active'?activeStage(d.stage):filter==='pay'?d.stage==='prepayment':filter==='production'?['production','ready'].includes(d.stage):true);
  return <><MobileHeader title="Сделки"/><div className="px-5 pb-24"><div className="flex gap-2 overflow-x-auto pb-2">{[['all','Все'],['active','Активные'],['pay','Ждут оплату'],['production','Производство']].map(([id,n])=><button key={id} onClick={()=>setFilter(id)} className={`shrink-0 rounded-full px-4 py-2 text-[10px] ${filter===id?'bg-[#232326] text-white':'bg-white'}`}>{n}</button>)}</div><div className="mt-2 grid grid-cols-4 gap-[6px]"><KpiMini label="Всего" value={deals.length} color="#ddeafb"/><KpiMini label="Активные" value={deals.filter(d=>activeStage(d.stage)).length} color="#ddefe4"/><KpiMini label="Оплата" value={deals.filter(d=>d.stage==='prepayment').length} color="#f7dde4"/><KpiMini label="Сумма" value={compactMoney(deals.reduce((s,d)=>s+d.amount,0)).replace(' ₽','').replace(' млн','м')} color="#e9e1fa"/></div><div className="mt-4 space-y-2">{shown.length?shown.map(d=><DealCard key={d.id} deal={d} open={()=>setSelectedDealId(d.id)}/>):<Empty text="Сделок пока нет"/>}</div></div></>;
};

const MobileDealDetail:React.FC<{deal:Deal;onBack:()=>void}>=({deal,onBack})=>{
  const{clients,documents,payments,updateDeal,updateDealStage}=useCrm();
  const client=clients.find(c=>c.id===deal.clientId);const docs=documents.filter(d=>d.dealId===deal.id);const paid=payments.filter(p=>p.dealId===deal.id&&p.direction==='inflow'&&p.status==='completed').reduce((s,p)=>s+p.amount,0);
  return <><MobileHeader title={deal.clientName} back={onBack}/><div className="px-5 pb-24"><div className="mb-3 flex gap-2 overflow-x-auto">{stageOrder.map(s=><button key={s} onClick={()=>updateDealStage(deal.id,s)} className="shrink-0 rounded-full px-3 py-2 text-[9px]" style={{background:deal.stage===s?stageMeta[s].dot:stageMeta[s].bg,color:deal.stage===s?'white':'#181a20'}}>{stageMeta[s].label}</button>)}</div><MobileCard className="p-4"><div className="text-[10px] text-[#7b808b]">Сделка</div><h2 className="mt-1 text-[16px] font-semibold">{deal.title}</h2><label className="mt-4 block text-[9px] text-[#7b808b]">Сумма</label><input type="number" value={deal.amount} onChange={e=>updateDeal(deal.id,{amount:Number(e.target.value)})} className="mt-1 w-full rounded-[12px] bg-[#fbfaf7] px-3 py-3 text-[18px] font-semibold outline-none"/><div className="mt-3 flex justify-between text-[10px]"><span className="text-[#7b808b]">Получено</span><b>{money(paid)}</b></div><div className="mt-3 flex justify-between text-[10px]"><span className="text-[#7b808b]">Срок</span><b>{shortDate(deal.deadline)}</b></div></MobileCard><MobileCard className="mt-4 p-4"><h2 className="text-[15px] font-semibold">Клиент</h2><div className="mt-3 text-[11px] leading-6"><b>{client?.company||client?.name||deal.clientName}</b><br/>{client?.phone||'Телефон не указан'}<br/>{client?.email||'Email не указан'}</div></MobileCard><MobileCard className="mt-4 p-4"><h2 className="text-[15px] font-semibold">Документы</h2><div className="mt-3 flex flex-wrap gap-2">{docs.map(d=><span key={d.id} className="rounded-full bg-[#f7f5f1] px-3 py-2 text-[10px]"><FileText size={11} className="mr-1 inline"/>{d.number}</span>)}{!docs.length&&<span className="text-[10px] text-[#8b8580]">Документов пока нет</span>}</div></MobileCard></div></>;
};

const MobileFunnel:React.FC=()=>{
  const{deals,setSelectedDealId,setCurrentTab}=useCrm();const[stage,setStage]=useState<DealStage>('lead');const grouped=deals.filter(d=>d.stage===stage);
  return <><MobileHeader title="Воронка"/><div className="px-5 pb-24"><div className="grid grid-cols-4 gap-[6px]"><KpiMini label="Лиды" value={deals.filter(d=>d.stage==='lead').length} color="#ddeafb"/><KpiMini label="КП" value={deals.filter(d=>d.stage==='proposal_sent').length} color="#f8e8d6"/><KpiMini label="Оплата" value={deals.filter(d=>d.stage==='prepayment').length} color="#f7dde4"/><KpiMini label="Произв." value={deals.filter(d=>d.stage==='production').length} color="#ddefe4"/></div><div className="mt-4 flex gap-2 overflow-x-auto pb-2">{stageOrder.slice(0,9).map(s=><button key={s} onClick={()=>setStage(s)} className={`shrink-0 rounded-full px-3 py-2 text-[9px] ${stage===s?'text-white':''}`} style={{background:stage===s?stageMeta[s].dot:stageMeta[s].bg}}>{stageMeta[s].label}</button>)}</div><MobileCard className="mt-2 p-3"><div className="mb-3 flex items-center justify-between"><h2 className="text-[16px] font-semibold">{stageMeta[stage].label}</h2><span className="text-[11px] text-[#7b808b]">{grouped.length}</span></div><div className="space-y-2">{grouped.length?grouped.map(d=><DealCard key={d.id} deal={d} open={()=>{setSelectedDealId(d.id);setCurrentTab('deals')}}/>):<Empty text="На этом этапе сделок нет"/>}</div></MobileCard></div></>;
};

const MobileEconomics:React.FC=()=>{
  const{deals,payments}=useCrm();const completed=payments.filter(p=>p.status==='completed');const inflow=completed.filter(p=>p.direction==='inflow').reduce((s,p)=>s+p.amount,0);const outflow=completed.filter(p=>p.direction==='outflow').reduce((s,p)=>s+p.amount,0);const profit=inflow-outflow;const margin=inflow?Math.round(profit/inflow*100):0;const projects=[...deals].filter(d=>d.amount>0).sort((a,b)=>b.amount-a.amount).slice(0,3);
  return <><MobileHeader title="Экономика" subtitle={monthLabel()}/><div className="px-5 pb-24"><div className="grid grid-cols-4 gap-[6px]"><KpiMini label="Получено" value={compactMoney(inflow).replace(' ₽','').replace(' млн','м')} color="#f8e8d6"/><KpiMini label="Расходы" value={compactMoney(outflow).replace(' ₽','').replace(' млн','м')} color="#f7dde4"/><KpiMini label="Результат" value={compactMoney(profit).replace(' ₽','').replace(' млн','м')} color="#ddefe4"/><KpiMini label="Маржа" value={`${margin}%`} color="#ddeafb"/></div><MobileCard className="mt-4 p-4"><h2 className="text-[16px] font-semibold">Фактические платежи</h2>{completed.length?completed.slice(0,5).map(p=><div key={p.id} className="mt-3 flex items-center justify-between rounded-[12px] bg-[#fbfaf7] px-3 py-3 text-[11px]"><span className="min-w-0 truncate">{p.clientName} · {p.dealTitle}</span><b className={`ml-3 whitespace-nowrap ${p.direction==='outflow'?'text-[#a95f68]':'text-[#4d7c62]'}`}>{p.direction==='outflow'?'−':'+'}{money(p.amount)}</b></div>):<Empty text="Платежей пока нет"/>}</MobileCard><MobileCard className="mt-4 p-4"><h2 className="text-[16px] font-semibold">По проектам</h2>{projects.length?projects.map(d=><div key={d.id} className="mt-3 rounded-[12px] bg-[#fbfaf7] p-3"><div className="flex justify-between text-[11px]"><b className="truncate">{d.clientName}</b><b className="ml-2 whitespace-nowrap">{compactMoney(d.amount)}</b></div><div className="mt-1 truncate text-[9px] text-[#7b808b]">{d.title}</div></div>):<Empty text="Проектов пока нет"/>}</MobileCard></div></>;
};

const MobileProjectCalc:React.FC=()=>{
  const{deals,payments,selectedDealId,setSelectedDealId}=useCrm();const deal=deals.find(d=>d.id===selectedDealId)||deals[0];
  if(!deal)return <><MobileHeader title="Расчёт проекта"/><div className="px-5"><Empty text="Сделок пока нет"/></div></>;
  const flow=payments.filter(p=>p.dealId===deal.id);const income=flow.filter(p=>p.direction==='inflow'&&p.status==='completed').reduce((s,p)=>s+p.amount,0);const outflow=flow.filter(p=>p.direction==='outflow'&&p.status==='completed').reduce((s,p)=>s+p.amount,0);const cost=outflow||deal.primeCost||0;const result=income-cost;
  return <><MobileHeader title="Расчёт проекта" subtitle="Только фактические данные"/><div className="px-5 pb-24"><MobileCard className="p-3"><select value={deal.id} onChange={e=>setSelectedDealId(e.target.value)} className="w-full bg-transparent text-[12px] font-semibold outline-none">{deals.map(d=><option key={d.id} value={d.id}>{d.clientName} — {d.title}</option>)}</select></MobileCard><div className="mt-4 grid grid-cols-4 gap-[6px]"><KpiMini label="Сделка" value={compactMoney(deal.amount).replace(' ₽','').replace(' млн','м')} color="#ddeafb"/><KpiMini label="Поступило" value={compactMoney(income).replace(' ₽','').replace(' млн','м')} color="#ddefe4"/><KpiMini label="Расходы" value={compactMoney(cost).replace(' ₽','').replace(' млн','м')} color="#f7dde4"/><KpiMini label="Результат" value={compactMoney(result).replace(' ₽','').replace(' млн','м')} color="#f8e8d6"/></div><MobileCard className="mt-4 p-4"><h2 className="text-[16px] font-semibold">Статьи сделки</h2>{deal.items.length?deal.items.map(item=><div key={item.id} className="mt-3 flex justify-between rounded-[12px] bg-[#fbfaf7] px-3 py-3 text-[11px]"><span className="min-w-0 truncate">{item.title}</span><b className="ml-3 whitespace-nowrap">{money(item.primeCost*item.quantity)}</b></div>):<Empty text="Статьи расходов не заполнены"/>}</MobileCard><MobileCard className="mt-4 p-4"><h2 className="text-[16px] font-semibold">Движение денег</h2>{flow.length?flow.map(p=><div key={p.id} className="mt-3 flex justify-between text-[11px]"><span>{shortDate(p.date)} · {p.dealTitle}</span><b className={p.direction==='outflow'?'text-[#a95f68]':'text-[#4d7c62]'}>{p.direction==='outflow'?'−':'+'}{money(p.amount)}</b></div>):<Empty text="Движений денег пока нет"/>}</MobileCard></div></>;
};

const MobileDocuments:React.FC=()=>{
  const{deals,documents,setIsCreateInvoiceOpen}=useCrm();const[dealId,setDealId]=useState(deals[0]?.id||'');const deal=deals.find(d=>d.id===dealId);const docs=documents.filter(d=>!dealId||d.dealId===dealId);
  return <><MobileHeader title="КП и договор" subtitle="Реальные документы CRM"/><div className="px-5 pb-24"><MobileCard className="p-4"><label className="text-[9px] text-[#7b808b]">Сделка</label>{deals.length?<select value={dealId} onChange={e=>setDealId(e.target.value)} className="mt-2 w-full rounded-[12px] bg-[#fbfaf7] px-3 py-3 text-[11px] outline-none">{deals.map(d=><option key={d.id} value={d.id}>{d.clientName} — {d.title}</option>)}</select>:<Empty text="Сначала создайте сделку"/>}{deal&&<div className="mt-3 text-[11px]"><b>{deal.clientName}</b><div className="text-[#7b808b]">{compactMoney(deal.amount)} · срок {shortDate(deal.deadline)}</div></div>}</MobileCard>{deal&&<button onClick={()=>setIsCreateInvoiceOpen(true)} className="mt-4 h-[54px] w-full rounded-[16px] bg-[#232326] text-[12px] font-medium text-white">Создать документ</button>}<MobileCard className="mt-4 p-4"><h2 className="text-[16px] font-semibold">Готовые документы</h2>{docs.length?<div className="mt-3 space-y-2">{docs.slice(0,5).map(d=><div key={d.id} className="flex items-center justify-between rounded-[12px] bg-[#f7f5f1] px-3 py-3 text-[10px]"><span className="truncate"><FileText size={11} className="mr-1 inline"/>{d.number} · {d.title}</span><b>{money(d.amount)}</b></div>)}</div>:<Empty text="Документов пока нет"/>}</MobileCard></div></>;
};

const MobileCalendar:React.FC=()=>{
  const{deals,payments,setSelectedDealId,setCurrentTab}=useCrm();const[weekStart,setWeekStart]=useState(()=>mondayOf(new Date()));const today=new Date();const weekEnd=new Date(weekStart.getTime()+6*DAY);const days=Array.from({length:7},(_,i)=>new Date(weekStart.getTime()+i*DAY));
  const projects=deals.filter(d=>['production','ready'].includes(d.stage)).map(deal=>{const p=[...payments].filter(x=>x.dealId===deal.id&&x.direction==='inflow'&&x.status==='completed').sort((a,b)=>+new Date(a.date)-+new Date(b.date))[0];if(!p||!deal.deadline)return null;const start=+new Date(p.date);const end=+new Date(deal.deadline);const progress=end>start?Math.max(0,Math.min(100,(Date.now()-start)/(end-start)*100)):100;return{deal,paid:p.date,progress}}).filter(Boolean) as {deal:Deal;paid:string;progress:number}[];
  return <><MobileHeader title="Календарь" subtitle={`${shortDate(weekStart.toISOString())} — ${shortDate(weekEnd.toISOString())}`}/><div className="px-5 pb-24"><div className="flex items-center justify-between"><button onClick={()=>setWeekStart(new Date(weekStart.getTime()-7*DAY))} className="rounded-full bg-white px-4 py-2 text-[10px]">‹ Неделя</button><button onClick={()=>setWeekStart(mondayOf(new Date()))} className="rounded-full bg-[#232326] px-4 py-2 text-[10px] text-white">Сегодня</button><button onClick={()=>setWeekStart(new Date(weekStart.getTime()+7*DAY))} className="rounded-full bg-white px-4 py-2 text-[10px]">Неделя ›</button></div><div className="mt-4 grid grid-cols-7 gap-1">{days.map(date=>{const isToday=date.toDateString()===today.toDateString();return <div key={date.toISOString()} className={`rounded-[10px] py-2 text-center ${isToday?'bg-[#f8e8d6]':'bg-white'}`}><b className="block text-[11px]">{date.getDate()}</b><span className="text-[8px] text-[#7b808b]">{new Intl.DateTimeFormat('ru-RU',{weekday:'short'}).format(date).replace('.','')}</span></div>})}</div><MobileCard className="mt-4 p-4"><h2 className="text-[16px] font-semibold">Проекты в производстве</h2><div className="mt-3 space-y-2">{projects.length?projects.map(({deal,paid,progress})=><button key={deal.id} onClick={()=>{setSelectedDealId(deal.id);setCurrentTab('deals')}} className="block w-full rounded-[12px] bg-[#fbfaf7] p-3 text-left"><div className="flex justify-between"><b className="min-w-0 truncate text-[11px]">{deal.clientName}</b><span className="ml-2 shrink-0 text-[9px] text-[#7b808b]">до {shortDate(deal.deadline)}</span></div><div className="mt-1 truncate text-[9px] text-[#7b808b]">{deal.title}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#eeeae6]"><div className="h-full rounded-full bg-[#8aaf96]" style={{width:`${progress}%`}}/></div><div className="mt-1 text-[8px] text-[#7b808b]">оплачено {shortDate(paid)} · {stageMeta[deal.stage].label.toLowerCase()}</div></button>):<Empty text="Оплаченных проектов в производстве нет"/>}</div></MobileCard></div></>;
};

const MobileSettings:React.FC=()=>{const{theme,toggleTheme,currentManager}=useCrm();return <><MobileHeader title="Настройки"/><div className="px-5 pb-24"><MobileCard className="p-4"><b className="text-[14px]">{currentManager.name}</b><p className="mt-1 text-[10px] text-[#7b808b]">{currentManager.role}</p></MobileCard><MobileCard className="mt-4 p-4"><div className="flex items-center justify-between"><span className="text-[12px]">Тема интерфейса</span><button onClick={toggleTheme} className="rounded-full bg-[#f7f5f1] px-4 py-2 text-[10px]">{theme==='light'?'Светлая':'Тёмная'}</button></div></MobileCard></div></>};

export const MobileCrmView:React.FC=()=>{
  const{currentTab}=useCrm();const[moreOpen,setMoreOpen]=useState(false);const tab=String(currentTab);let page:React.ReactNode;
  if(tab==='dashboard')page=<MobileDashboard/>;else if(tab==='deals')page=<MobileDeals/>;else if(tab==='pipeline')page=<MobileFunnel/>;else if(tab==='finance')page=<MobileEconomics/>;else if(tab==='project_calc')page=<MobileProjectCalc/>;else if(tab==='documents')page=<MobileDocuments/>;else if(tab==='calendar')page=<MobileCalendar/>;else page=<MobileSettings/>;
  return <div className="mx-auto min-h-[100dvh] w-full max-w-[430px] overflow-x-hidden bg-[#f7f5f1] text-[#181a20]">{page}<MobileBottomNav moreOpen={moreOpen} setMoreOpen={setMoreOpen}/></div>;
};
