import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Loader2, RefreshCw, Send, Sparkles } from 'lucide-react';
import { useCrm } from '../../context/CrmContext';

type Thread={key:string;id:string;channel:'email'|'telegram';contactId:string|null;title:string;subtitle:string;unread:number;lastMessageAt:string;snippet:string;lastDirection:string};
type Message={id:string;direction:'incoming'|'outgoing';body:string;at:string};

const when=(v:string)=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('ru-RU',d.toDateString()===new Date().toDateString()?{hour:'2-digit',minute:'2-digit'}:{day:'2-digit',month:'short'}).format(d)};
const Header:React.FC<{title:string;onBack:()=>void;right?:React.ReactNode}>=({title,onBack,right})=><header className="sticky top-0 z-20 flex h-[66px] items-center gap-3 border-b border-[#e8e4de] bg-[#f7f5f1]/95 px-4 backdrop-blur"><button onClick={onBack} className="grid h-9 w-9 place-items-center rounded-full bg-white"><ArrowLeft size={16}/></button><h1 className="min-w-0 flex-1 truncate text-[20px] font-semibold">{title}</h1>{right}</header>;

export const MobileLiveInbox:React.FC=()=>{
  const{setCurrentTab}=useCrm();
  const[threads,setThreads]=useState<Thread[]>([]);const[selected,setSelected]=useState<string|null>(null);const[messages,setMessages]=useState<Message[]>([]);const[title,setTitle]=useState('');const[contactId,setContactId]=useState<string|null>(null);const[draft,setDraft]=useState('');const[loading,setLoading]=useState(true);const[sending,setSending]=useState(false);const[syncing,setSyncing]=useState(false);const endRef=useRef<HTMLDivElement|null>(null);
  const load=async()=>{setLoading(true);try{const[emailR,tgR]=await Promise.all([fetch('/api/inbox?filter=client',{cache:'no-store'}),fetch('/api/messages/telegram',{cache:'no-store'})]);const email=await emailR.json();const tg=await tgR.json();const list:Thread[]=[...(email.threads||[]).map((t:any)=>({key:`email:${t.id}`,id:String(t.id),channel:'email' as const,contactId:t.contactId||null,title:t.remoteName||t.remoteEmail||'Почта',subtitle:t.subject||t.remoteEmail||'',unread:Number(t.unreadCount||0),lastMessageAt:t.lastMessageAt||'',snippet:t.lastSnippet||'',lastDirection:t.lastDirection||''})),...(tg.threads||[]).map((t:any)=>({key:`telegram:${t.id}`,id:String(t.id),channel:'telegram' as const,contactId:t.contactId||t.id,title:t.remoteName||'Telegram',subtitle:t.remoteHandle||'Telegram',unread:Number(t.unreadCount||0),lastMessageAt:t.lastMessageAt||'',snippet:t.lastSnippet||'',lastDirection:t.lastDirection||''}))].sort((a,b)=>b.unread-a.unread||+new Date(b.lastMessageAt)-+new Date(a.lastMessageAt));setThreads(list);if(!selected&&list[0])setSelected(list[0].key)}finally{setLoading(false)}};
  const open=async(key:string)=>{setSelected(key);const[prefix,id]=key.split(':',2);if(prefix==='telegram'){const r=await fetch(`/api/messages/telegram/${encodeURIComponent(id)}`,{cache:'no-store'});const d=await r.json();setTitle(d.contact?.name||d.thread?.remoteName||'Telegram');setContactId(d.contact?.id||id);setMessages((d.messages||[]).map((m:any)=>({id:String(m.id),direction:m.direction,body:m.bodyText||'',at:m.receivedAt||''})));}else{const r=await fetch(`/api/inbox/${encodeURIComponent(id)}`,{cache:'no-store'});const d=await r.json();setTitle(d.contact?.name||d.thread?.remoteName||d.thread?.remoteEmail||'Почта');setContactId(d.contact?.id||d.thread?.contactId||null);setMessages((d.messages||[]).map((m:any)=>({id:String(m.id),direction:m.direction,body:m.bodyText||'',at:m.receivedAt||''})));}requestAnimationFrame(()=>endRef.current?.scrollIntoView({block:'end'}));};
  useEffect(()=>{void load()},[]);useEffect(()=>{if(selected)void open(selected)},[selected]);
  const selectedThread=threads.find(t=>t.key===selected);
  const send=async()=>{if(!draft.trim()||!selectedThread)return;setSending(true);try{const text=draft.trim();let r:Response;if(selectedThread.channel==='telegram')r=await fetch('/api/integrations/telegram/reply',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contactId,text})});else r=await fetch(`/api/inbox/${encodeURIComponent(selectedThread.id)}/reply`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text})});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||'Не удалось отправить');}setDraft('');await open(selectedThread.key);await load();}finally{setSending(false)}};
  const sync=async()=>{setSyncing(true);try{await fetch('/api/integrations/email/sync',{method:'POST'});await load();}finally{setSyncing(false)}};
  if(selectedThread&&messages.length>=0&&title)return <div className="min-h-[100dvh] bg-[#f7f5f1]"><Header title={title} onBack={()=>{setSelected(null);setTitle('');setMessages([])}} right={<span className="rounded-full bg-white px-3 py-2 text-[9px] text-[#7b808b]">{selectedThread.channel==='telegram'?'Telegram':'Email'}</span>}/><div className="px-4 pb-28 pt-4"><div className="space-y-2">{messages.map(m=><div key={m.id} className={`max-w-[84%] rounded-[16px] px-3 py-2.5 text-[11px] leading-5 ${m.direction==='outgoing'?'ml-auto bg-[#232326] text-white':'bg-white'}`}><div className="whitespace-pre-wrap break-words">{m.body}</div><div className={`mt-1 text-[8px] ${m.direction==='outgoing'?'text-white/60':'text-[#9a938d]'}`}>{when(m.at)}</div></div>)}<div ref={endRef}/></div></div><div className="fixed bottom-0 left-0 right-0 z-30 mx-auto flex max-w-[430px] gap-2 border-t border-[#e8e4de] bg-white p-3"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}} className="min-w-0 flex-1 rounded-full bg-[#f7f5f1] px-4 py-3 text-[12px] outline-none" placeholder="Сообщение..."/><button disabled={sending} onClick={()=>void send()} className="grid h-11 w-11 place-items-center rounded-full bg-[#232326] text-white">{sending?<Loader2 size={15} className="animate-spin"/>:<Send size={15}/>}</button></div></div>;
  return <div className="min-h-[100dvh] bg-[#f7f5f1]"><Header title="Чаты" onBack={()=>setCurrentTab('dashboard')} right={<button onClick={()=>void sync()} className="grid h-9 w-9 place-items-center rounded-full bg-white">{syncing?<Loader2 size={14} className="animate-spin"/>:<RefreshCw size={14}/>}</button>}/><div className="px-4 py-4"><div className="mb-3 flex items-center justify-between text-[10px] text-[#7b808b]"><span>{threads.length} диалогов</span><span>{threads.reduce((s,t)=>s+t.unread,0)} непрочитанных</span></div>{loading?<div className="grid h-40 place-items-center"><Loader2 className="animate-spin"/></div>:<div className="space-y-2">{threads.map((t,i)=><button key={t.key} onClick={()=>void open(t.key)} className="flex w-full items-center rounded-[16px] border border-[#e8e4de] bg-white p-3 text-left"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-full text-[11px] ${t.channel==='telegram'?'bg-[#ddeafb]':'bg-[#f8e8d6]'}`}>{t.title.slice(0,1).toUpperCase()}</span><span className="ml-3 min-w-0 flex-1"><span className="flex items-center"><b className="truncate text-[12px]">{t.title}</b><span className="ml-auto text-[9px] text-[#8b8580]">{when(t.lastMessageAt)}</span></span><span className="mt-1 block truncate text-[10px] text-[#7b808b]">{t.snippet||t.subtitle}</span></span>{t.unread>0&&<span className="ml-2 grid h-5 min-w-5 place-items-center rounded-full bg-[#232326] px-1 text-[9px] text-white">{t.unread}</span>}</button>)}</div>}</div></div>;
};

export const MobileLiveEva:React.FC=()=>{
  const{setCurrentTab}=useCrm();const[input,setInput]=useState('');const[items,setItems]=useState<{role:'user'|'assistant';text:string}[]>([]);const[busy,setBusy]=useState(false);const endRef=useRef<HTMLDivElement|null>(null);
  const ask=async(text?:string)=>{const message=(text??input).trim();if(!message||busy)return;setItems(v=>[...v,{role:'user',text:message}]);setInput('');setBusy(true);try{const r=await fetch('/api/assistant',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'chat',message})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Ева не ответила');setItems(v=>[...v,{role:'assistant',text:String(d.answer||d.message||d.response||'Готово')}]);}catch(e){setItems(v=>[...v,{role:'assistant',text:e instanceof Error?e.message:'Ошибка связи с Евой'}]);}finally{setBusy(false);requestAnimationFrame(()=>endRef.current?.scrollIntoView({block:'end'}));}};
  const quick=['Что требует внимания сегодня?','Кто ждёт оплаты?','Какие КП надо дожать?','Сделай сводку по активным сделкам'];
  return <div className="min-h-[100dvh] bg-[#f7f5f1]"><Header title="Ева ✦" onBack={()=>setCurrentTab('dashboard')} right={<span className="rounded-full bg-[#e9e1fa] px-3 py-2 text-[9px]">AI менеджер</span>}/><div className="px-4 pb-28 pt-4">{!items.length&&<><div className="rounded-[18px] border border-[#e8e4de] bg-white p-4"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#e9e1fa]"><Sparkles size={15}/></span><b className="text-[13px]">Работаю с живой CRM</b></div><p className="mt-3 text-[11px] leading-5 text-[#625c57]">Вижу реальные сделки, переписку и документы через подключённый AI-менеджер. Спроси, что нужно сделать.</p></div><div className="mt-3 grid grid-cols-2 gap-2">{quick.map(q=><button key={q} onClick={()=>void ask(q)} className="rounded-[14px] border border-[#e8e4de] bg-white p-3 text-left text-[10px] leading-4">{q}</button>)}</div></>}
    <div className="mt-4 space-y-2">{items.map((m,i)=><div key={i} className={`max-w-[88%] whitespace-pre-wrap rounded-[16px] px-3 py-2.5 text-[11px] leading-5 ${m.role==='user'?'ml-auto bg-[#232326] text-white':'bg-white'}`}>{m.text}</div>)}{busy&&<div className="flex w-fit items-center gap-2 rounded-[16px] bg-white px-3 py-2 text-[10px] text-[#7b808b]"><Loader2 size={13} className="animate-spin"/>Ева думает…</div>}<div ref={endRef}/></div></div><div className="fixed bottom-0 left-0 right-0 z-30 mx-auto flex max-w-[430px] gap-2 border-t border-[#e8e4de] bg-white p-3"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void ask()}}} className="min-w-0 flex-1 rounded-full bg-[#f7f5f1] px-4 py-3 text-[12px] outline-none" placeholder="Дать задачу Еве..."/><button disabled={busy} onClick={()=>void ask()} className="grid h-11 w-11 place-items-center rounded-full bg-[#232326] text-white"><Send size={15}/></button></div></div>;
};
